name: my_app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_core: ^2.24.2
  get: ^4.6.6
  form_field_validator: ^1.1.0
  google_sign_in: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

  # Add custom fonts here if you have any.
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700

flutter_native_splash:
  color: "#00007f" # Splash ekranının arka plan rengi

flutter_launcher_icons:
  android: true
  ios: true
  image_path: lib/assets/logo.png # Uygulama simgesi olarak kullanılacak resim
